### ISSUE TITLE
Continuous Integration and Deployment on Jenkins

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-cm#37]
https://ci.eris.industries/ for e-cm and e-db

- [ ] move unit testing from CircleCI to Jenkins
- [ ] integrate network testing harnass in Jenkins
- [ ] separate deployment process from push to master
- [ ] clean build deliverable

**Comment by compleatang** [comment]
closing for now as this repo will be deprecated.
